config/routes.rb
Rails.application.routes.draw do
  resources :places

  resources :interesses

  resources :pessoas
  get "home/new_release" => 'home#new_release', :as => :new_release
  get "/home", to: "pages#home", as: "home"
  get "/geocoding", to: "pages#geocoding", as: "geocoding"
  get "/reverse_geocoding", to: "pages#reverse_geocoding", as: "reverse_geocoding"
  get 'home/tabs' => 'home#tabs'
  get 'home/locais' => 'home#locais'
  get "home/map_release" => 'home#map_release', :as => :map_release
  get "home/map_more" => 'home#map_more', :as => :map_more

  get 'home/index'

  devise_for :users

   root 'home#index'

end

app/models/interess.rb
class Interess < ActiveRecord::Base
  has_and_belongs_to_many :pessoas
  has_and_belongs_to_many :places
end

app/models/pessoa.rb
class Pessoa < ActiveRecord::Base
  validates :nome, :endereco, :presence => true 
  validates :user_id, :presence => true, :uniqueness => true
  belongs_to :user
  has_and_belongs_to_many :interesses
  geocoded_by :endereco
  after_validation :geocode

protected
  def possui_user?
    user = current_user.pessoa.present?
  end
end

app/models/place.rb
class Place < ActiveRecord::Base
  has_and_belongs_to_many :interesses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 has_one :pessoa
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  API_KEY = "AIzaSyAJmHMNL_ElGdY9YguNoZOS0qw-uYfz_fY"
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    
  end


  def locais

    respond_to do |format|
     format.js 
    end	
  end

  def tabs
    respond_to do |format|
     format.js 
    end	
  end

  def map_release
    @latitude = params[:lat]
    @longitude = params[:lng]
    respond_to do |format|
      format.js
    end
  end

  def new_release
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/interesses_controller.rb
class InteressesController < ApplicationController
  before_action :set_interess, only: [:show, :edit, :update, :destroy]

  # GET /interesses
  # GET /interesses.json
  def index
    @interesses = Interess.all
  end

  # GET /interesses/1
  # GET /interesses/1.json
  def show
  end

  # GET /interesses/new
  def new
    @interess = Interess.new
  end

  # GET /interesses/1/edit
  def edit
  end

  # POST /interesses
  # POST /interesses.json
  def create
    @interess = Interess.new(interess_params)

    respond_to do |format|
      if @interess.save
        format.html { redirect_to @interess, notice: 'Interesse was successfully created.' }
        format.json { render action: 'show', status: :created, location: @interess }
      else
        format.html { render action: 'new' }
        format.json { render json: @interess.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interesses/1
  # PATCH/PUT /interesses/1.json
  def update
    respond_to do |format|
      if @interess.update(interess_params)
        format.html { redirect_to @interess, notice: 'Interesse was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @interess.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interesses/1
  # DELETE /interesses/1.json
  def destroy
    @interess.destroy
    respond_to do |format|
      format.html { redirect_to interesses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interess
      @interess = Interess.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interess_params
      params.require(:interess).permit(:nome, :descricao, :place_ids => [])
    end
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.all
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
    respond_to do |format|               
      format.js
      format.html
    end
  end

  # GET /pessoas/new
  def new
    if current_user.pessoa.present?
      @pessoa = Pessoa.find_by_user_id(current_user.id)
      render :action => 'edit'
    else
    @pessoa = Pessoa.new
    end
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)
    @pessoa.user_id = current_user.id

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully created.' }
        format.json { render :show, status: :created, location: @pessoa }
      else
        format.html { render :new }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Pessoa was successfully updated.' }
        format.json { render :show, status: :ok, location: @pessoa }
      else
        format.html { render :edit }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.destroy
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Pessoa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:nome, :idade, :endereco, :user_id, :interess_ids => [])
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:tipo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interesses_helper.rb
module InteressesHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/home/_estabelecimento.html.erb
<ul>
<%@client.each do |spot|%>
<li><%= spot.name%></li>
<%end%>
</ul>

app/views/home/_locais.html.erb
    <%@client = GooglePlaces::Client.new("AIzaSyAJmHMNL_ElGdY9YguNoZOS0qw-uYfz_fY")%>
   <%@spot_id = params[:spot_id]%>
    <%@client = @client.spots(current_user.pessoa.latitude,current_user.pessoa.longitude,:radius => '500', :types => [interesse.to_s])%>
<% if @client.present? %>
  <ul>
    <%@client.each do |spot|%>
      <%= hidden_field_tag "search_box_geocoding", "#{spot.lat}" %>
      <li><%= link_to "#{spot.name}", map_release_path(:lat => spot.lat, :lng => spot.lng), {:id => "submit_button_geocoding", :remote => true}  %></li>
      
    <%end%>
 
  </ul>
<%end%>

app/views/home/_map_release.html.erb
<p align=center>
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{latitude}%2C#{longitude}"  %>
</p>

app/views/home/_new_release.erb
 <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Modal header</h3>
  </div>
  <div class="modal-body">
    **here comes whatever you want to show!**
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>

app/views/home/index.html.erb
<%if user_signed_in?%>
<% if current_user.pessoa.present?%>
  <h3>A seguir você encontrará locais próximos a você</h3>
<%= form_tag(home_tabs_path, :method => 'get', :remote => true, :'data-update-target' => 'update-   container') do %>
    <p>
     <%= submit_tag 'Localizar locais proximos', :disable_with => 'Please wait...',:id => 'locais', :class => 'btn btn-primary' %>
    </p>
  <% end %>
<%else%>
<p><%= ("Realize o cadastro. #{link_to "Clique Aqui", new_pessoa_path}").html_safe%></p>
<%end%>
<br/>
<p>
<h2>Locais Próximos a você</h2>
    <ul class="nav nav-tabs" role="tablist">
      <li class="active"><a href="#home" role="tab" data-toggle="tab">Home</a></li>
    </ul>
    <div class="tab-content">
      <div class="tab-pane active" id="home">
	  <h1>Você está aqui:</h1>
	  <%= current_user.pessoa.endereco%>
          <%= hidden_field_tag "search_box_geocoding", current_user.pessoa.endereco %>
	<p>
	<button class="demo btn btn-primary btn-lg" href="#responsive" data-toggle="modal" id = "submit_button_geocoding" >Ver Mapa</button>
	</p>
      </div>
    </div>
<%end%>

app/views/home/index.js.erb
BootstrapDialog.show({
    message: 'Hi Apple!'
});

app/views/home/locais.html.erb
<ul>
<%@client.each do |spot|%>
<li><%= spot.name%></li>
<%end%>
</ul>

app/views/home/map_more.js.erb
$('#spot').append("<%= escape_javascript(render :partial => 'locais')%>");

app/views/home/map_release.js.erb
$('#map-container').html("<%= escape_javascript(render :partial => 'map_release', :locals => {:latitude => @latitude, :longitude => @longitude})%>");
$('#responsive').modal();

app/views/home/new_release.js.erb
$("#modal-window").html("<%= escape_javascript(render 'home/new_release') %>");

app/views/home/tabs.js.erb
<% current_user.pessoa.interesses.each do |i|%>
$('.nav-tabs').append('<li><%= link_to i.nome.capitalize, "##{i.nome.downcase}" , { :role=>"tab","data-toggle" => "tab", :remote => true} %></li>');
$('.tab-content').append('<div id="<%= i.nome.downcase %>" class="tab-pane"><div id="spot<%= i.id%>"><%= escape_javascript(render :partial => 'locais', :locals => {:interesse => i.nome} )%></div></div>');


<%end%>

app/views/interesses/_form.html.erb
<%= form_for(@interess) do |f| %>
  <% if @interess.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interess.errors.count, "error") %> prohibited this interess from being saved:</h2>

      <ul>
      <% @interess.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br>
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interesses/edit.html.erb
<h1>Editing interess</h1>

<%= render 'form' %>

<%= link_to 'Show', @interess %> |
<%= link_to 'Back', interesses_path %>

app/views/interesses/index.html.erb
<h1>Listing interesses</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @interesses.each do |interess| %>
      <tr>
        <td><%= interess.nome %></td>
        <td><%= interess.descricao %></td>
        <td><%= interess.user %></td>
        <td><%= link_to 'Show', interess %></td>
        <td><%= link_to 'Edit', edit_interess_path(interess) %></td>
        <td><%= link_to 'Destroy', interess, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Interesse', new_interess_path %>

app/views/interesses/new.html.erb
<h1>New interess</h1>

<%= render 'form' %>

<%= link_to 'Back', interesses_path %>

app/views/interesses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @interess.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @interess.descricao %>
</p>

<p>
  <strong>User:</strong>
  <%= @interess.user %>
</p>

<%= link_to 'Edit', edit_interess_path(@interess) %> |
<%= link_to 'Back', interesses_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
  <% if user_signed_in? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" id="dropdownMenu1">
        Conta <b class="caret"></b>
      </a>

      <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
        <li role="presentation" class="dropdown-header"><%= link_to "Perfil", edit_user_registration_path %></li>
	<li role="presentation" class="dropdown-header"><%= link_to "Sair", destroy_user_session_path, :method => :delete %></li>
      </ul>
    </li>
</div>    
  <% else %>
    <li role="presentation" class="dropdown-header"><%= link_to "Entrar", new_user_session_path %></li>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TCC" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "TCC" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header>
      <%= render 'layouts/navigation' %>
    </header>   
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
<p>
    <div id="responsive" class="modal fade" tabindex="-1" data-width="760" style="display: none;">
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    
    </div>
    <div class="modal-body">
    <div class="row">
    <div class="col-md-6">
<div>
<div id="map-container">
	<div id="map-canvas"></div>
</div>
    </div>
    </div>
    </div>
    <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn btn-default">Fechar</button>
    </div>
    </div>
</p>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa) do |f| %>
  <% if @pessoa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pessoa.errors.count, "error") %> prohibited this pessoa from being saved:</h2>

      <ul>
      <% @pessoa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, 'data-provide'=>"typeahead" %>
  </div>
  <div class="field">
    <%= f.label :idade %><br>
    <%= f.number_field :idade %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>

<table class="tabelas">
<th colspan="2" style=" font-size: large; color: blue">Interesses</th>
<% Interess.all.in_groups_of(5, false) do |row_interesses| %>
<tr>
<% row_interesses.each do |interesse| %>
<td><%= check_box_tag "pessoa[interess_ids][]", interesse.id, @pessoa.interesses.include?(interesse) %> <%= interesse.nome %></td>
<% end %>
</tr>
<%end%>
</table>

  <div class="actions">
    <%= f.submit "Salvar", :class => "btn"%>
  </div>
<% end %>

app/views/pessoas/edit.html.erb
<h1>Editing pessoa</h1>

<%= render 'form' %>

<%= link_to 'Show', @pessoa %> |
<%= link_to 'Back', pessoas_path %>

app/views/pessoas/index.html.erb
<h1>Listing pessoas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Idade</th>
      <th>Endereco</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td><%= pessoa.idade %></td>
        <td><%= pessoa.endereco %></td>
        <td><%= pessoa.user %></td>
        <td><%= link_to 'Show', pessoa %></td>
        <td><%= link_to 'Edit', edit_pessoa_path(pessoa) %></td>
        <td><%= link_to 'Destroy', pessoa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pessoa', new_pessoa_path %>

app/views/pessoas/new.html.erb
<h1>New pessoa</h1>

<%= render 'form' %>

<%= link_to 'Back', pessoas_path %>

app/views/pessoas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @pessoa.nome %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @pessoa.idade %>
</p>
<p>
  <strong>Endereco:</strong>
  <%= @pessoa.endereco %>
  <%= hidden_field_tag "search_box_geocoding", @pessoa.endereco%>
</p>
<p>
<button class="demo btn btn-primary btn-lg" href="#responsive" data-toggle="modal" id = "submit_button_geocoding" >Ver Mapa</button>
</p>



<%= link_to 'Voltar', pessoas_path %>

app/views/pessoas/show.js.erb
$('#geocoding_fields').show();
$('#geocoding').addClass('active');
$("#submit_button_geocoding").hide();

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% @place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.tipo %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @place.tipo %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>